version: '2.1'
services:
  database:
    restart: always
    image: mysql:9.3.0
    environment:
      - MYSQL_DATABASE=subscription_manager
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    container_name: subscription_manager_db

  test_database:
    image: mysql:9.3.0
    environment:
      - MYSQL_DATABASE=subscription_manager_test
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3308:3306"
    container_name: subscription_manager_db_test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DEV_DATABASE_URL=mysql+pymysql://root:@database:3306/subscription_manager
    ports:
      - '8080:8000'
    depends_on:
      - database 
    container_name: subscription_manager


  test:
    build: .
    entrypoint: ["/app/entrypoint.sh"] 
    depends_on:
      test_database:
        condition: service_healthy
    environment:
      - DEV_DATABASE_URL=mysql+pymysql://root:@test_database:3306/subscription_manager_test
      - TEST_DATABASE_URL=mysql+pymysql://root:@test_database:3306/subscription_manager_test
      - FLASK_ENV=testing
      - SECRET_KEY=secret
    command: ["pytest"]