"""empty message

Revision ID: 0d583bd5d137
Revises: 24e4dc3ffdf1
Create Date: 2025-05-11 23:54:42.688615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d583bd5d137'
down_revision = '24e4dc3ffdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index('plan_unique_name_content', ['name'], unique=True)

    op.create_table('plan_intervals',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('plan_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('interval', sa.Enum('one_time', 'day', 'week', 'month', 'year'), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('interval_count >= 0', name='check_interval_count_non_zero'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'plan_id', name='unique_plan_interval_plan_id')
    )
    op.create_table('plan_interval_prices',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('interval_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('currency', mysql.CHAR(length=3), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interval_id'], ['plan_intervals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interval_id', 'currency', name='uq_interval_currency')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_interval_prices')
    op.drop_table('plan_intervals')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index('plan_unique_name_content')

    op.drop_table('plans')
    # ### end Alembic commands ###
