"""empty message

Revision ID: 3dc96d402af5
Revises: 0d583bd5d137
Create Date: 2025-05-12 23:13:59.596975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dc96d402af5'
down_revision = '0d583bd5d137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_upgrades',
    sa.Column('old_plan_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('new_plan_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['new_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['old_plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('old_plan_id', 'new_plan_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('plan_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('price_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('interval', sa.Enum('one_time', 'day', 'week', 'month', 'year'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'cancelled', 'ended'), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('upgraded_from_subscription_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['plan_interval_prices.id'], ),
    sa.ForeignKeyConstraint(['upgraded_from_subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('plan_upgrades')
    # ### end Alembic commands ###
