"""empty message

Revision ID: a5d83fd9dfc5
Revises: 3dc96d402af5
Create Date: 2025-05-13 13:02:15.727830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d83fd9dfc5'
down_revision = '3dc96d402af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_plan_id', ['plan_id'], unique=False)
        batch_op.create_index('idx_plan_id_status', ['plan_id', 'status'], unique=False)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_id_plan_id', ['user_id', 'plan_id'], unique=False)
        batch_op.create_index('idx_user_id_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_id_status')
        batch_op.drop_index('idx_user_id_plan_id')
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('idx_plan_id_status')
        batch_op.drop_index('idx_plan_id')

    # ### end Alembic commands ###
